### ISSUE TITLE
Community docs to-do

### ISSUE THREAD

**Issue by evanwill** [CollectionBuilder/cb-issues#2]
- [x] code of conduct (jd) drafted
- [x] contributing (ew) drafted
- [ ] issue/PR templates (ew)
- [x] license on root page (ew)

**Comment by jylisadoney** [comment]
The Code of Conduct is included at CollectionBuilder/

**Comment by jylisadoney** [comment]
I added the code of conduct to the cd-issues repository until it is finalized.

**Comment by evanwill** [comment]
I moved these drafts to cb.io since they are good to go!
